keys:
  - &admin_cody 881CEAC38C98647F6F660956794D748B8B8BF912
  - &host_arnold age1fd2pv8mgmej7peex64wncrxflkpd0mj4mewzv330gljy5cemws6sqngde8
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *admin_cody
  - path_regex: hosts/arnold/.*$
    key_groups:
    - pgp:
      - *admin_cody
      age:
      - *host_arnold
