# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "aic79xx" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "calvin/local/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "calvin/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    {
      device = "calvin/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D6E6-B9F1";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    {
      device = "calvin/nix";
      fsType = "zfs";
    };

  swapDevices = [ ];

}
